builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - files:
      - configs/*
      - user-files/**
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'

