##########################
#  Alfred Configuration  #
##########################

# This file contains all the settings configurable for Alfred with their default values.

# Core options.
[core]
# mocks-dir = "user-files/mocks/" # Mocks' folder